RegisterNetEvent('q:coms:time')
AddEventHandler('q:coms:time', function(hour, minute)
    NetworkOverrideClockTime(hour, minute, 0) 
end)

RegisterNetEvent('q:coms:weather')
AddEventHandler('q:coms:weather', function(weatherType)
    SetWeatherTypeNow(weatherType)
    SetOverrideWeather(weatherType)
    ClearWeatherTypePersist()
    SetRainLevel(0.0)
    SetWind(0.0)
    SetWindSpeed(0.0)
end)